coverage:
  ignore:
    - "**/*.g.cs"
    - "**/Crews.PlanningCenter.Api.DocParser/Configuration/**"
    - "**/Crews.PlanningCenter.Api.DocParser/Models/**"
    - "**/Crews.PlanningCenter.Api.DocParser/Program.cs"
    - "**/Crews.PlanningCenter.Api/Api/V2018_08_01/Organization.cs"
    - "**/Crews.PlanningCenter.Api/Services/ArrangementSection.cs"
    - "**/Crews.PlanningCenter.Api/Authentication/PlanningCenterTokenHandler.cs"
