using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
class PlanningCenterRootClientsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<AdditionalText> jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".json"));
        
        IncrementalValuesProvider<(string Directory, Models.Version Version)> parsedFiles = jsonFiles
            .Select((file, ct) =>
            {
                string content = file.GetText(ct)?.ToString() ?? string.Empty;
                Models.Version version = JsonSerializer.Deserialize<Models.Version>(content) 
                    ?? throw new InvalidOperationException($"Failed to deserialize {file.Path}");
                
                string directory = Path.GetFileName(Path.GetDirectoryName(file.Path));
                
                return (directory, version);
            });

        IncrementalValuesProvider<(ProductDefinition Product, ImmutableArray<Models.Version> Versions)> products = parsedFiles
            .Collect()
            .SelectMany((files, ct) => files
                .GroupBy(f => f.Directory)
                .Select(group => (
                    Product: ProductDefinition.All.First(p => group.Key.Equals(p.ToString().ToPascalCase())),
                    Versions: group.Select(f => f.Version).ToImmutableArray()
                )));

        context.RegisterSourceOutput(products, static (context, product) =>
        {
            (ProductDefinition Product, ImmutableArray<Models.Version> Versions) = product;
            string fileName = $"{Product.ToString().ToPascalCase()}.Client";
            StringBuilder sb = new();
            using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
            GenerateRootClient(writer, new()
            {
                Name = Product,
                Versions = Versions
            });
            string sourceCode = sb.ToString();

            context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        });
    }

    private static void GenerateRootClient(IndentedTextWriter writer, Product product)
    {
        string productName = product.Name.ToString().ToPascalCase();
        string latestVersionId = product.Versions
            .OrderByDescending(v => v.Id)
            .First()
            .Id;
        string latestVersionName = "V" + latestVersionId.Replace('-', '_');

        string summary = $"Client for accessing the Planning Center {productName} API.";
        summary = summary.ToXmlSummary();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Net.Http;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Crews.Web.JsonApiClient;");
        writer.WriteLine("using Crews.PlanningCenter.Api.Extensions;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api;");
        writer.WriteLine();

        string clientClassName = $"{productName}Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Client for accessing the Planning Center {productName} API.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {clientClassName}(HttpClient httpClient)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Gets a client for the latest version ({latestVersionId}) of the {productName} API.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public Crews.PlanningCenter.Api.{productName}.{latestVersionName}.OrganizationClient Latest");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("get");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"httpClient.DefaultRequestHeaders.SetPlanningCenterVersion(\"{latestVersionId}\");");
        writer.WriteLine($"return new Crews.PlanningCenter.Api.{productName}.{latestVersionName}.OrganizationClient(");
        writer.Indent++;
        writer.WriteLine("httpClient,");
        writer.WriteLine($"new(httpClient.BaseAddress ?? new(\"https://api.planningcenteronline.com/\"), \"{product.Name}/v2/\"));");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        foreach (Models.Version version in product.Versions)
        {
            GenerateVersionNavProperty(writer, product.Name, version);
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateVersionNavProperty(IndentedTextWriter writer, ProductDefinition product, Models.Version version)
    {
        string productName = product.ToString().ToPascalCase();

        string versionString = "V" + version.Id.Replace('-', '_');
        
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Gets a client for version {version.Id} of the {productName} API.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public Crews.PlanningCenter.Api.{productName}.{versionString}.OrganizationClient {versionString}");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("get");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"httpClient.DefaultRequestHeaders.SetPlanningCenterVersion(\"{version.Id}\");");
        writer.WriteLine($"return new Crews.PlanningCenter.Api.{productName}.{versionString}.OrganizationClient(");
        writer.Indent++;
        writer.WriteLine("httpClient,");
        writer.WriteLine($"new(httpClient.BaseAddress ?? new(\"https://api.planningcenteronline.com/\"), \"{product}/v2/\"));");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }
}