using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Text;
using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
class PlanningCenterResourceClientsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(ProductDefinition Product, Version? version)> products = context
            .GetVersionsProvider();

        context.RegisterSourceOutput(
            products.Where(static x => x.version != null),
            static (context, tuple) =>
            {
                StringBuilder sb = new();
                (ProductDefinition product, Version? version) = tuple;
                string productName = product.ToString().ToPascalCase();

                if (version is null) return;

                string fileName = $"{productName}.{version.Id}.Clients";

                using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
                GenerateFile(writer, productName, version);
                string sourceCode = sb.ToString();

                context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
    }

    private static void GenerateFile(IndentedTextWriter writer, string productName, Version version)
    {
        string versionString = "V" + version.Id.Replace('-', '_');

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Net.Http;");
        writer.WriteLine("using System.Net.Http.Json;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Nodes;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Crews.PlanningCenter.Api.Models;");
        writer.WriteLine("using Crews.Web.JsonApiClient;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api.{productName}.{versionString};");
        writer.WriteLine();

        foreach (Resource resource in version.Resources.Where(r => r.ShouldGenerateClients))
        {
            GenerateResourceClients(writer, resource);
            GenerateResponseClasses(writer, resource);
        }
    }

    private static void GenerateResourceClients(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Client for interacting with the {resource.AttributesClrType} resource.";
        summary = summary.ToXmlSummary();
        
        string modelType = resource.AttributesClrType;
        string responseType = modelType + "Response";
        string resourceType = resource.ResourceClrType;
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");

        if (resource.Deprecated)
        {
            writer.WriteLine("[Obsolete(\"This resource is deprecated and may be removed in a future version.\")]");
        }

        writer.WriteLine($"public class {clientType}(HttpClient httpClient, Uri uri)");
        writer.Indent++;
        writer.WriteLine($": SingletonResourceClient<{modelType}, {resourceType}, {responseType}>(httpClient, uri)");
        writer.Indent--;
        writer.WriteLine("{");
        writer.Indent++;

        foreach (ResourceChild child in resource.Children)
            GenerateChildNavigation(writer, child);

        GenerateEndpointMethods(writer, resource, modelType, responseType);

        foreach (ResourceAction action in resource.Actions)
            GenerateActionMethod(writer, action);

        foreach (ResourceIncludable includable in resource.CanInclude)
            GenerateIncludable(writer, includable, modelType);

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        summary = $"Client for interacting with {modelType} collection resources.";
        summary = summary.ToXmlSummary();

        string collectionResponseType = modelType + "CollectionResponse";
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");

        if (resource.Deprecated)
        {
            writer.WriteLine("[Obsolete(\"This resource is deprecated and may be removed in a future version.\")]");
        }

        writer.WriteLine($"public class Paginated{clientType}(HttpClient httpClient, Uri uri)");
        writer.Indent++;
        writer.WriteLine($": PaginatedResourceClient<{modelType}, {resourceType}, {collectionResponseType}, {responseType}>(httpClient, uri)");
        writer.Indent--;
        writer.WriteLine("{");
        writer.Indent++;        

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Fetches a paginated list of <see cref=\"{modelType}\"/> resources asynchronously.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
        writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing a paginated list of <see cref=\"{modelType}\"/> resources.</returns>");
        writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
        writer.WriteLine($"public new Task<{collectionResponseType}> GetAsync(CancellationToken cancellationToken = default) => base.GetAsync(cancellationToken);");
        writer.WriteLine();

        if (resource.Postable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"resource\">The resource data to be sent in the POST request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the created <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PostAsync({modelType} resource, CancellationToken cancellationToken = default) => base.PostAsync(resource, cancellationToken);");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"document\">The JSON:API document to be sent in the POST request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the created <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PostAsync(JsonApiDocument<{resource.ResourceClrType}> document, CancellationToken cancellationToken = default) => base.PostAsync(document, cancellationToken);");
            writer.WriteLine();
        }

        if (!resource.CollectionOnly)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new instance of a {modelType} client for a specific resource ID.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"id\">The ID of the resource to create a client for.</param>");
            writer.WriteLine("/// <returns>A new instance of the resource client for the specified resource ID.</returns>");
            writer.WriteLine($"public {clientType} WithId(string id) => new (HttpClient, new(Uri, $\"{{id}}/\"));");
            writer.WriteLine();
        }

        foreach (ResourceIncludable includable in resource.CanInclude)
            GenerateIncludable(writer, includable, modelType);

        foreach (ResourceOrderable orderable in resource.CanOrderBy)
            GenerateOrderable(writer, orderable, modelType);

        foreach (ResourceQueryable queryable in resource.CanQueryBy)
            GenerateQueryable(writer, queryable, modelType);

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateResponseClasses(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Response model for {resource.AttributesClrType.ToPascalCase()} resource.".ToXmlSummary();

        string modelType = resource.AttributesClrType.ToPascalCase();
        string resourceType = resource.ResourceClrType.ToPascalCase();
        string responseType = modelType + "Response";
        string collectionResponseType = modelType + "CollectionResponse";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {responseType} : ResourceResponse<{resourceType}> {{ }}");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Collection {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {collectionResponseType} : ResourceResponse<IEnumerable<{resourceType}>> {{ }}");
        writer.WriteLine();
    }

    private static void GenerateChildNavigation(IndentedTextWriter writer, ResourceChild child)
    {
        string type = child.AttributesClrType + "Client";
        if (child.IsCollection) type = "Paginated" + type;

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {child.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");

        if (child.Deprecated)
        {
            writer.WriteLine("[Obsolete(\"This endpoint is deprecated and may be removed in a future release.\")]");
        }

        writer.WriteLine($"public {type} {child.ClrName} => new(HttpClient, new(Uri, \"{child.JsonName}/\"));");
        writer.WriteLine();
    }

    private static void GenerateIncludable(IndentedTextWriter writer, ResourceIncludable includable, string modelType)
    {
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {includable.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {includable.ClrMethodName}() => ({clientType})AddQueryParameter(\"include\", \"{includable.Value}\");");
        writer.WriteLine();
    }

    private static void GenerateOrderable(IndentedTextWriter writer, ResourceOrderable orderable, string modelType)
    {
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {orderable.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {orderable.ClrMethodName}() => ({clientType})ReplaceQueryParameter(\"order\", \"{orderable.Value}\");");
        writer.WriteLine();

        orderable.Description += " Use reverse order.";
        orderable.ClrMethodName += "Descending";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {orderable.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {orderable.ClrMethodName}() => ({clientType})ReplaceQueryParameter(\"order\", \"-{orderable.Value}\");");
        writer.WriteLine(); 
    }

    private static void GenerateQueryable(IndentedTextWriter writer, ResourceQueryable queryable, string modelType)
    {
        string clientType = modelType + "Client";
        string valueParameter = "value";

        if (queryable.ClrType.Contains("DateTime"))
        {
            valueParameter += ".ToString(\"o\")";
        }
        else if (queryable.ClrType.Contains("DateOnly"))
        {
            valueParameter += ".ToString(\"yyyy-MM-dd\")";
        }
        else if (queryable.ClrType != "string")
        {
            valueParameter += ".ToString()";
        }

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {queryable.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {queryable.ClrMethodName}({queryable.ClrType} value) => ({clientType})ReplaceQueryParameter(\"{queryable.Parameter}\", {valueParameter});");
        writer.WriteLine();
    }

    private static void GenerateEndpointMethods(IndentedTextWriter writer, Resource resource, string modelType, string responseType)
    {   
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Fetches the <see cref=\"{modelType}\"/> resource asynchronously.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
        writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the <see cref=\"{modelType}\"/> resource.</returns>");
        writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
        writer.WriteLine($"public new Task<{responseType}> GetAsync(CancellationToken cancellationToken = default) => base.GetAsync(cancellationToken);");
        writer.WriteLine();

        if (resource.Patchable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Updates an existing <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"resource\">The resource data to be sent in the patch request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the updated <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PatchAsync({modelType} resource, CancellationToken cancellationToken = default) => base.PatchAsync(resource, cancellationToken);");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Updates an existing <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"document\">The JSON:API document to be sent in the patch request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the updated <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PatchAsync(JsonApiDocument<{resource.ResourceClrType}> document, CancellationToken cancellationToken = default) => base.PatchAsync(document, cancellationToken);");
            writer.WriteLine();
        }

        if (resource.Deletable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Deletes the <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine("/// <returns>A task representing the asynchronous delete operation.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task DeleteAsync(CancellationToken cancellationToken = default) => base.DeleteAsync(cancellationToken);");
            writer.WriteLine();
        }
    }

    private static void GenerateActionMethod(IndentedTextWriter writer, ResourceAction action)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {action.Description.ToXmlSummary()}");
        if (!string.IsNullOrEmpty(action.AdditionalDetails))
        {
            writer.WriteLine($"/// <br/>{action.AdditionalDetails!.ToXmlSummary()}");
        }
        writer.WriteLine("/// </summary>");

        if (action.Deprecated)
        {
            writer.WriteLine("[Obsolete(\"This action is deprecated and may be removed in a future release.\")]");
        }

        writer.WriteLine($"public Task {action.ClrMethodName}(CancellationToken cancellationToken = default) => base.PostAsync(new(Uri, \"{action.Path}\"), cancellationToken);");
        writer.WriteLine();
    } 
}
