using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
internal class PlanningCenterModelsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Get all additional files that are JSON files
        IncrementalValuesProvider<AdditionalText> jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".json"));

        // Step 2: Read and parse the JSON files
        IncrementalValuesProvider<(string fileName, ApiDefinition? definition)> apiDefinitions =
            jsonFiles.Select(static (file, cancellationToken) =>
            {
                string fileName = System.IO.Path.GetFileNameWithoutExtension(file.Path);
                SourceText? text = file.GetText(cancellationToken);

                if (text == null)
                    return (fileName, null);

                try
                {
                    var definition = JsonSerializer.Deserialize<ApiDefinition>(
                        text.ToString(),
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                    );
                    return (fileName, definition);
                }
                catch
                {
                    return (fileName, null);
                }
            });

        // Step 3: Filter out nulls and generate source
        context.RegisterSourceOutput(
            apiDefinitions.Where(static x => x.definition != null),
            static (context, tuple) =>
            {
                var (fileName, definition) = tuple;
                if (definition == null) return;

                // Generate C# source code from the definition
                string sourceCode = GenerateApiClient(definition);

                context.AddSource(
                    $"{fileName}.g.cs",
                    SourceText.From(sourceCode, Encoding.UTF8)
                );
            });
    }

    private static string GenerateApiClient(ApiDefinition definition)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace PlanningCenter.Api.{definition.Product}");
        sb.AppendLine("{");

        // Generate models
        foreach (var model in definition.Models ?? [])
        {
            GenerateModel(sb, model);
        }

        // Generate API client
        GenerateClient(sb, definition);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateModel(StringBuilder sb, ModelDefinition model)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {EscapeXmlComment(model.Description ?? model.Name)}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public class {model.Name}");
        sb.AppendLine("    {");

        foreach (var property in model.Properties ?? [])
        {
            string propertyType = MapJsonTypeToCSharp(property.Type, property.IsNullable);

            if (!string.IsNullOrEmpty(property.Description))
            {
                _ = sb.AppendLine($"        /// <summary>{EscapeXmlComment(property.Description ?? string.Empty)}</summary>");
            }

            sb.AppendLine($"        public {propertyType} {property.Name} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateClient(StringBuilder sb, ApiDefinition definition)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Client for {definition.Product} API v{definition.Version}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public class {definition.Product}Client");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly string _baseUrl;");
        sb.AppendLine("        private readonly string _apiToken;");
        sb.AppendLine();
        sb.AppendLine($"        public {definition.Product}Client(string apiToken, string baseUrl = \"https://api.planningcenteronline.com/{definition.Product.ToLower()}/v{definition.Version}\")");
        sb.AppendLine("        {");
        sb.AppendLine("            _apiToken = apiToken ?? throw new ArgumentNullException(nameof(apiToken));");
        sb.AppendLine("            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate endpoint methods
        foreach (var endpoint in definition.Endpoints ?? [])
        {
            GenerateEndpointMethod(sb, endpoint);
        }

        sb.AppendLine("    }");
    }

    private static void GenerateEndpointMethod(StringBuilder sb, EndpointDefinition endpoint)
    {
        string? returnType = string.IsNullOrEmpty(endpoint.ResponseType)
            ? "void"
            : endpoint.ResponseType;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// {EscapeXmlComment(endpoint.Description ?? endpoint.Name)}");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public async System.Threading.Tasks.Task<{returnType}> {endpoint.Name}Async()");
        sb.AppendLine("        {");
        sb.AppendLine($"            // TODO: Implement {endpoint.Method} {endpoint.Path}");
        sb.AppendLine("            throw new NotImplementedException();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string MapJsonTypeToCSharp(string jsonType, bool isNullable)
    {
        string csharpType = jsonType?.ToLowerInvariant() switch
        {
            "string" => "string",
            "integer" or "int" => "int",
            "long" => "long",
            "boolean" or "bool" => "bool",
            "number" or "decimal" => "decimal",
            "datetime" or "date-time" => "DateTime",
            "array" => "List<object>",
            "object" => "object",
            _ => jsonType ?? "object"
        };

        if (isNullable && csharpType != "string")
        {
            return $"{csharpType}?";
        }

        return csharpType;
    }

    private static string EscapeXmlComment(string text)
    {
        return text?.Replace("<", "&lt;").Replace(">", "&gt;") ?? "";
    }
}

// Data models for deserializing your JSON files
public class ApiDefinition
{
    public string Product { get; set; } = "";
    public string Version { get; set; } = "";
    public ModelDefinition[]? Models { get; set; }
    public EndpointDefinition[]? Endpoints { get; set; }
}

public class ModelDefinition
{
    public string Name { get; set; } = "";
    public string? Description { get; set; }
    public PropertyDefinition[]? Properties { get; set; }
}

public class PropertyDefinition
{
    public string Name { get; set; } = "";
    public string Type { get; set; } = "";
    public string? Description { get; set; }
    public bool IsNullable { get; set; }
}

public class EndpointDefinition
{
    public string Name { get; set; } = "";
    public string Method { get; set; } = "";
    public string Path { get; set; } = "";
    public string? Description { get; set; }
    public string? ResponseType { get; set; }
}
