using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
internal class PlanningCenterModelsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(ProductDefinition Product, Models.Version? Version)> products =
            Providers.GetVersionsProvider(context);

        context.RegisterSourceOutput(
            products.Where(static x => x.Version != null),
            static (context, tuple) =>
            {
                StringBuilder sb = new();
                (ProductDefinition product, Models.Version? version) = tuple;
                string productName = product.ToString().ToPascalCase();

                if (version is null) return;

                string fileName = $"{productName}.{version.Id}.Models";

                using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
                GenerateVersionModels(writer, productName, version);
                string sourceCode = sb.ToString();

                context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
    }

    private static void GenerateVersionModels(IndentedTextWriter writer, string productName, Models.Version version)
    {
        string versionString = "V" + version.Id.Replace('-', '_');

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Nodes;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api.{productName}.{versionString};");
        writer.WriteLine();

        foreach (Resource resource in version.Resources)
        {
            GenerateResourceModel(writer, resource);
        }
    }

    private static void GenerateResourceModel(IndentedTextWriter writer, Resource resource)
    {
        if (resource.Attributes.Any(a => a.Name.ToPascalCase() == resource.Name))
        {
            resource.Name += "Resource";
            resource.Description += 
                "NOTE: The name of this class has been modified because it contains a property with the same name.";
        }

        string summary = resource.Description is null 
            ? "Planning Center does not provide a description for this resource." 
            : resource.Description.ToXmlSummary();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {resource.Name}");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (ResourceAttribute attribute in resource.Attributes)
        {
            GenerateAttributeProperty(writer, attribute);
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateAttributeProperty(IndentedTextWriter writer, ResourceAttribute attribute)
    {
        string summary = attribute.Description is null 
            ? "Planning Center does not provide a description for this attribute." 
            : attribute.Description.ToXmlSummary();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {attribute.Type.ToClrType()}? {attribute.Name.ToPascalCase()} {{ get; set; }}");
        writer.WriteLine();
    }
}
