using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
class PlanningCenterResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(ProductDefinition Product, Version? Version)> products = context
            .GetVersionsProvider();

        context.RegisterSourceOutput(
            products.Where(static x => x.Version != null),
            static (context, tuple) =>
            {
                StringBuilder sb = new();
                (ProductDefinition product, Version? version) = tuple;
                string productName = product.ToString().ToPascalCase();

                if (version is null) return;

                string fileName = $"{productName}.{version.Id}.Resources";

                using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
                GenerateVersionModels(writer, productName, version);
                string sourceCode = sb.ToString();

                context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
    }

    private static void GenerateVersionModels(IndentedTextWriter writer, string productName, Version version)
    {
        string versionString = "V" + version.Id.Replace('-', '_');

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Nodes;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Crews.Web.JsonApiClient;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api.{productName}.{versionString};");
        writer.WriteLine();

        foreach (Resource resource in version.Resources.Where(r => r.GenerateResource))
        {
            GenerateResourceModel(writer, resource);
            GenerateResourceAttributesModel(writer, resource);
            GenerateResourceRelationshipsModel(writer, resource);
        }
    }

    private static void GenerateResourceModel(IndentedTextWriter writer, Resource resource)
    {
        string summary = resource.Description is null 
            ? "Planning Center does not provide a description for this resource." 
            : resource.Description.ToXmlSummary();

        string modelType = resource.Name.ToPascalCase();
        string resourceType = resource.ResourceName.ToPascalCase();
        string relationshipsType = modelType + "Relationships";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {resourceType} : JsonApiResource");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("/// <inheritdoc/>");
        writer.WriteLine($"[JsonPropertyName(\"attributes\")]");
        writer.WriteLine($"public required new {modelType} Attributes {{ get; init; }}");
        if (resource.Relationships.Any())
        {
            writer.WriteLine();
            writer.WriteLine("/// <inheritdoc/>");
            writer.WriteLine($"[JsonPropertyName(\"relationships\")]");
            writer.WriteLine($"public new {relationshipsType}? Relationships {{ get; init; }}");
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateResourceAttributesModel(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Attributes for the {resource.Name} resource.";

        string className = resource.Name.ToPascalCase();;
        summary = summary.ToXmlSummary();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {className}");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (ResourceAttribute attribute in resource.Attributes)
        {
            if (attribute.Name.ToPascalCase() == className)
            {
                attribute.Name += "_attribute";
                attribute.Description = (attribute.Description 
                    ?? "Planning Center does not provide a description for this attribute.") 
                    + "\nNOTE: The name of this property has been modified because the class shares its original name.";
            }
            GenerateAttributeProperty(writer, attribute);
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateAttributeProperty(IndentedTextWriter writer, ResourceAttribute attribute)
    {
        string summary = attribute.Description is null 
            ? "Planning Center does not provide a description for this attribute." 
            : attribute.Description.ToXmlSummary();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"[JsonPropertyName(\"{attribute.Name}\")]");
        writer.WriteLine($"public {attribute.Type.ToClrType()}? {attribute.Name.ToPascalCase()} {{ get; set; }}");
        writer.WriteLine();
    }

    private static void GenerateResourceRelationshipsModel(IndentedTextWriter writer, Resource resource)
    {
        if (!resource.Relationships.Any()) return;

        string summary = $"Relationships for the {resource.Name} resource.".ToXmlSummary();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {resource.Name.ToPascalCase()}Relationships");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (ResourceRelationship relationship in resource.Relationships)
        {
            GenerateRelationshipProperty(writer, relationship);
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }
    private static void GenerateRelationshipProperty(IndentedTextWriter writer, ResourceRelationship relationship)
    {
        string summary = relationship.Note is null
            ? $"Related {relationship.Name.ToPascalCase()}."
            : relationship.Note.ToXmlSummary();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"[JsonPropertyName(\"{relationship.Name}\")]");
        writer.WriteLine($"public JsonApiRelationship? {relationship.Name.ToPascalCase()} {{ get; set; }}");
        writer.WriteLine();
    }
}
