using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Text;
using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
class PlanningCenterResourceClientsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(ProductDefinition Product, Version? version)> products = context
            .GetVersionsProvider();

        context.RegisterSourceOutput(
            products.Where(static x => x.version != null),
            static (context, tuple) =>
            {
                StringBuilder sb = new();
                (ProductDefinition product, Version? version) = tuple;
                string productName = product.ToString().ToPascalCase();

                if (version is null) return;

                string fileName = $"{productName}.{version.Id}.Clients";

                using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
                GenerateFile(writer, productName, version);
                string sourceCode = sb.ToString();

                context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
    }

    private static void GenerateFile(IndentedTextWriter writer, string productName, Version version)
    {
        string versionString = "V" + version.Id.Replace('-', '_');

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Net.Http;");
        writer.WriteLine("using System.Net.Http.Json;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Nodes;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Crews.PlanningCenter.Api.Models;");
        writer.WriteLine("using Crews.Web.JsonApiClient;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api.{productName}.{versionString};");
        writer.WriteLine();

        foreach (Resource resource in version.Resources.Where(r => r.GenerateClients))
        {
            GenerateResourceClients(writer, resource);
            GenerateResponseClasses(writer, resource);
        }
    }

    private static void GenerateResourceClients(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Client for interacting with the {resource.Name} resource.";
        if (resource.Deprecated) summary = $"DEPRECATED: {summary}";
        summary = summary.ToXmlSummary();
        
        string modelType = resource.Name.ToPascalCase();
        string responseType = modelType + "Response";
        string resourceType = resource.ResourceName.ToPascalCase();
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {clientType}(HttpClient httpClient, Uri uri)");
        writer.Indent++;
        writer.WriteLine($": SingletonResourceClient<{modelType}, {resourceType}, {responseType}>(httpClient, uri)");
        writer.Indent--;
        writer.WriteLine("{");
        writer.Indent++;

        foreach (ResourceChild child in resource.Children)
            GenerateChildNavigation(writer, child);

        GenerateEndpointMethods(writer, resource, modelType, responseType);

        foreach (ResourceIncludable includable in resource.CanInclude)
            GenerateIncludable(writer, includable, modelType);

        foreach (ResourceOrderable orderable in resource.CanOrderBy)
            GenerateOrderable(writer, orderable, modelType);

        foreach (ResourceQueryable queryable in resource.CanQueryBy)
            GenerateQueryable(writer, queryable, modelType);

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        summary = $"Client for interacting with {modelType} collection resources.";
        if (resource.Deprecated) summary = $"DEPRECATED: {summary}";
        summary = summary.ToXmlSummary();

        string collectionResponseType = modelType + "CollectionResponse";
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class Paginated{modelType}Client(HttpClient httpClient, Uri uri)");
        writer.Indent++;
        writer.WriteLine($": PaginatedResourceClient<{modelType}, {resourceType}, {collectionResponseType}, {responseType}>(httpClient, uri)");
        writer.Indent--;
        writer.WriteLine("{");
        writer.Indent++;        
       
        if (resource.Postable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"resource\">The resource data to be sent in the POST request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the created <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PostAsync({modelType} resource, CancellationToken cancellationToken = default) => base.PostAsync(resource, cancellationToken);");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"document\">The JSON:API document to be sent in the POST request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the created <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PostAsync(JsonApiDocument<{resource.ResourceName}> document, CancellationToken cancellationToken = default) => base.PostAsync(document, cancellationToken);");
            writer.WriteLine();
        }

        if (!resource.CollectionOnly)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Creates a new instance of a {modelType} client for a specific resource ID.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"id\">The ID of the resource to create a client for.</param>");
            writer.WriteLine("/// <returns>A new instance of the resource client for the specified resource ID.</returns>");
            writer.WriteLine($"public {clientType} WithId(string id) => new (HttpClient, new(Uri, $\"{{id}}/\"));");
            writer.WriteLine();
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateResponseClasses(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Response model for {resource.Name.ToPascalCase()} resource.".ToXmlSummary();

        string modelType = resource.Name.ToPascalCase();
        string resourceType = resource.ResourceName.ToPascalCase();
        string responseType = modelType + "Response";
        string collectionResponseType = modelType + "CollectionResponse";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {responseType} : ResourceResponse<{resourceType}> {{ }}");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Collection {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public class {collectionResponseType} : ResourceResponse<IEnumerable<{resourceType}>> {{ }}");
        writer.WriteLine();
    }

    private static void GenerateChildNavigation(IndentedTextWriter writer, ResourceChild child)
    {
        string memberName = child.Name.ToPascalCase();

        string summary = child.Description is null
            ? $"Related {memberName}."
            : child.Description;
        if (child.IsDeprecated) summary = $"DEPRECATED: {summary}";
        summary = summary.ToXmlSummary();

        string type = child.Type.ToPascalCase() + "Client";
        if (child.IsCollection) type = "Paginated" + type;

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {type} {child.Name.ToPascalCase()} => new(HttpClient, new(Uri, \"{child.Name}/\"));");
        writer.WriteLine();
    }

    private static void GenerateIncludable(IndentedTextWriter writer, ResourceIncludable includable, string modelType)
    {
        string summary = includable.Description ?? $"Include related {includable.Value.ToPascalCase()}.";
        if (includable.CanAssignOnCreate) summary += "\nCan also be used when creating this resource type.";
        if (includable.CanAssignOnUpdate) summary += "\nCan also be used when updating this resource type.";
        summary = summary.ToXmlSummary();

        string methodName = "Include" + includable.Value.ToPascalCase();
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {methodName}() => ({clientType})SetQueryParameter(\"{includable.Parameter}\", \"{includable.Value}\");");
        writer.WriteLine();
    }

    private static void GenerateOrderable(IndentedTextWriter writer, ResourceOrderable orderable, string modelType)
    {
        string summary = $"Order by {orderable.Value.ToPascalCase()}.";

        string methodName = "OrderBy" + orderable.Value.Replace(".", "").ToPascalCase();
        string clientType = modelType + "Client";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {methodName}() => ({clientType})SetQueryParameter(\"{orderable.Parameter}\", \"{orderable.Value}\");");
        writer.WriteLine();

        summary += " Use reverse order.";
        methodName += "Descending";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {methodName}() => ({clientType})SetQueryParameter(\"{orderable.Parameter}\", \"-{orderable.Value}\");");
        writer.WriteLine(); 
    }

    private static void GenerateQueryable(IndentedTextWriter writer, ResourceQueryable queryable, string modelType)
    {
        string methodName = "Where" + queryable.Name.ToPascalCase();
        string clientType = modelType + "Client";

        string summary = queryable.Description ?? $"Query by {queryable.Name.ToPascalCase()}.";
        if (queryable.Example is not null)
        {
            string exampleValue = queryable.Example.Split('=')[1];
            string example = $"Example: {methodName}(\"{exampleValue}\")";
            summary += $"\n{example}";
        }
        summary = summary.ToXmlSummary();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public {clientType} {methodName}(string value) => ({clientType})SetQueryParameter(\"{queryable.Parameter}\", value);");
        writer.WriteLine();
    }

    private static void GenerateEndpointMethods(IndentedTextWriter writer, Resource resource, string modelType, string responseType)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Fetches the <see cref=\"{modelType}\"/> resource asynchronously.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
        writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the <see cref=\"{modelType}\"/> resource.</returns>");
        writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
        writer.WriteLine($"public new Task<{responseType}> GetAsync(CancellationToken cancellationToken = default) => base.GetAsync(cancellationToken);");
        writer.WriteLine();

        if (resource.Patchable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Updates an existing <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"resource\">The resource data to be sent in the patch request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the updated <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PatchAsync({modelType} resource, CancellationToken cancellationToken = default) => base.PatchAsync(resource, cancellationToken);");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Updates an existing <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"document\">The JSON:API document to be sent in the patch request.</param>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine($"/// <returns>A task representing the asynchronous operation, containing the updated <see cref=\"{modelType}\"/> resource.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task<{responseType}> PatchAsync(JsonApiDocument<{resource.ResourceName}> document, CancellationToken cancellationToken = default) => base.PatchAsync(document, cancellationToken);");
            writer.WriteLine();
        }

        if (resource.Deletable)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// Deletes the <see cref=\"{modelType}\"/> resource asynchronously.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"cancellationToken\">A token to monitor for cancellation requests.</param>");
            writer.WriteLine("/// <returns>A task representing the asynchronous delete operation.</returns>");
            writer.WriteLine("/// <exception cref=\"JsonApiException\">Thrown when the HTTP response indicates a failure status code.</exception>");
            writer.WriteLine($"public new Task DeleteAsync(CancellationToken cancellationToken = default) => base.DeleteAsync(cancellationToken);");
            writer.WriteLine();
        }
    } 
}
