using Crews.PlanningCenter.Api.Generators.Extensions;
using Crews.PlanningCenter.Api.Models;
using Crews.PlanningCenter.Api.Models.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Text;

namespace Crews.PlanningCenter.Api.Generators;

[Generator]
class PlanningCenterResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(ProductDefinition Product, Version? Version)> products = context
            .GetVersionsProvider();

        context.RegisterSourceOutput(
            products.Where(static x => x.Version != null),
            static (context, tuple) =>
            {
                StringBuilder sb = new();
                (ProductDefinition product, Version? version) = tuple;
                string productName = product.ToString().ToPascalCase();

                if (version is null) return;

                string fileName = $"{productName}.{version.Id}.Resources";

                using IndentedTextWriter writer = new(new StringWriter(sb), "    ");
                GenerateVersionModels(writer, productName, version);
                string sourceCode = sb.ToString();

                context.AddSource($"{fileName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
    }

    private static void GenerateVersionModels(IndentedTextWriter writer, string productName, Version version)
    {
        string versionString = "V" + version.Id.Replace('-', '_');

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Nodes;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Crews.Web.JsonApiClient;");
        writer.WriteLine();
        writer.WriteLine($"namespace Crews.PlanningCenter.Api.{productName}.{versionString};");
        writer.WriteLine();

        foreach (Resource resource in version.Resources.Where(r => r.ShouldGenerateResource))
        {
            GenerateResourceModel(writer, resource);
            GenerateResourceAttributesModel(writer, resource);
            GenerateResourceRelationshipsModel(writer, resource);
        }
    }

    private static void GenerateResourceModel(IndentedTextWriter writer, Resource resource)
    {
        string relationshipsType = resource.AttributesClrType + "Relationships";

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {resource.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        if (resource.Relationships.Any())
        {
            writer.WriteLine($"public partial record {resource.ResourceClrType} : JsonApiResource<{resource.AttributesClrType}, {relationshipsType}> {{ }}");
        }
        else
        {
            writer.WriteLine($"public partial record {resource.ResourceClrType} : JsonApiResource<{resource.AttributesClrType}> {{ }}");
        }
        writer.WriteLine();
    }

    private static void GenerateResourceAttributesModel(IndentedTextWriter writer, Resource resource)
    {
        string summary = $"Attributes for the {resource.AttributesClrType} resource.";
        summary = summary.ToXmlSummary();

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public partial record {resource.AttributesClrType}");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (ResourceAttribute attribute in resource.Attributes)
        {
            if (attribute.ClrName == resource.AttributesClrType)
            {
                attribute.ClrName += "Attribute";
                attribute.Description +=
                    "\nNOTE: The name of this property has been modified because the type shares its original name.";
            }
            GenerateAttributeProperty(writer, attribute);
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateAttributeProperty(IndentedTextWriter writer, ResourceAttribute attribute)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {attribute.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");

        if (attribute.JsonConverter is not null)
        {
            writer.WriteLine($"[JsonConverter(typeof({attribute.JsonConverter}))]");
        }

        writer.WriteLine("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
        writer.WriteLine($"[JsonPropertyName(\"{attribute.JsonName}\")]");
        writer.WriteLine($"public {attribute.ClrType}? {attribute.ClrName} {{ get; init; }}");
        writer.WriteLine();
    }

    private static void GenerateResourceRelationshipsModel(IndentedTextWriter writer, Resource resource)
    {
        if (!resource.Relationships.Any()) return;

        string summary = $"Relationships for the {resource.AttributesClrType} resource.".ToXmlSummary();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public partial record {resource.AttributesClrType}Relationships");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (ResourceRelationship relationship in resource.Relationships)
        {
            GenerateRelationshipProperty(writer, resource, relationship);
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void GenerateRelationshipProperty(IndentedTextWriter writer, Resource resource, ResourceRelationship relationship)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {relationship.Description.ToXmlSummary()}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
        writer.WriteLine($"[JsonPropertyName(\"{relationship.JsonName}\")]");

        if (relationship.IsCollection)
        {
            writer.WriteLine($"public JsonApiCollectionRelationship<{relationship.ClrResourceType}>? {relationship.ClrName} {{ get; init; }}");
            writer.WriteLine();
            return;
        }
        writer.WriteLine($"public JsonApiRelationship<{relationship.ClrResourceType}>? {relationship.ClrName} {{ get; init; }}");
        writer.WriteLine();
    }
}
