on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        dotnet test Crews.PlanningCenter.Api.Tests --configuration Release --collect:"XPlat Code Coverage"
        dotnet test Crews.PlanningCenter.Api.DocParser.Tests --configuration Release --collect:"XPlat Code Coverage"
        dotnet test Crews.PlanningCenter.Api.Generators.Tests --configuration Release --collect:"XPlat Code Coverage"
        dotnet test Crews.PlanningCenter.Api.Models.Tests --configuration Release --collect:"XPlat Code Coverage"
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    name: Run integration tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      env:
        PlanningCenter__AppId: ${{ secrets.PLANNINGCENTER_APP_ID }}
        PlanningCenter__Secret: ${{ secrets.PLANNINGCENTER_SECRET }}
      run: dotnet test Crews.PlanningCenter.Api.IntegrationTests --configuration Release
